### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by rdp** [barisbalic/crystal-docs-web#2]
seemed to be just now...

**Comment by barisbalic** [comment]
Yes!  Unfortunately you are right, a reset of the underlying hardware took it out, it came back up and for reasons I could not easily ascertain the project no longer served static files.

I was going to fix it, but instead I've rewritten it to clone repos and build automatically, which I hope to put online later tonight or some time tomorrow, just ironing out a bug now.

Thanks very much for reporting it, I'll leave this issue open until I push a working release of the new code!

**Comment by barisbalic** [comment]
@rdp @miketheman thanks again for reporting this, I've thrown up a new version of the site, it now pulls repos from github when they are first requested and tries to build them against the last 8 releases of Crystal, there are some issues to resolve and some things to clean up before I push the code but for now... the docs are back up!

**Comment by miketheman** [comment]
Thanks for the update, happy to help where possible!

**Comment by rdp** [comment]
Thanks!
