### ISSUE TITLE
poor links

### ISSUE THREAD

**Issue by rdp** [barisbalic/crystal-docs-web#3]
It would be nice if the link

Example: https://crystal-docs.org/sdogruyol/kemal

 on 

https://crystal-docs.org/

linked to that page :)

Also the links here are 404's: https://crystal-docs.org/about
Cheers!

**Comment by barisbalic** [comment]
Ah, yes, so what's actually happened is that this codebase is now deprecated, and the new version sits in another repo, which I'll make public tonight.  I may overwrite this one altogether, but I remain undecided as yet.

You're right, the link on the homepage might as well be a real link!

**Comment by barisbalic** [comment]
Thanks again for your time, I've applied your feedback in the new project found here: https://github.com/barisbalic/crystal-docs

I'll close this now but feel free to open issues there.
