### ISSUE TITLE
The actual resource is down. Is this going to be supported ?

### ISSUE THREAD

**Issue by veelenga** [barisbalic/crystal-docs-web#4]
![image](https://cloud.githubusercontent.com/assets/3624712/20649390/aaf0fd48-b4c7-11e6-8165-1cad578cfa8e.png)

**Comment by andrewhamon** [comment]
Still down...

**Comment by barisbalic** [comment]
Hey, thanks both of you for posting, I was making some changes to the way documentation was compiled on the machine, when my laptop faulted and died, I've been moving between machines since and have only just got a proper replacement sorted.  I will get things running again this week and give you both an update!

**Comment by veelenga** [comment]
@barisbalic please take your time, no hurry. Thank you for response and nice project ;)

**Comment by barisbalic** [comment]
@veelenga @andrewhamon thanks very much for your patience, the site should now be available once more.  It's actually a different codebase, located here: https://github.com/barisbalic/crystal-docs if you'd like to leave any feedback in future.

I did notice that crystal versions greater than 0.19.4 were not building as expected, I will take a look at that this weekend, at that point I'll probably destroy this repo.

**Comment by barisbalic** [comment]
The issue with later versions turned out to be a permissions issue on disk that was easily fixed, so I'm going to close this thread and leave it here a few days so you get a chance to read it before I nuke this project.  Thanks again for your enthusiasm, and if you'd like to contribute, please do!

**Comment by veelenga** [comment]
Great. Thanks for fixing it 👍
